//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICASBulletin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SICASBulletin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///#reporte {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}	
        ///
        ///table {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}
        ///
        ///td {
        ///	padding: .5em;
        ///	text-align: right;
        ///}
        ///
        ///td:first-child {
        ///	padding: .5em;
        ///	text-align: left;
        ///}
        ///
        ///th {
        ///	padding: .5em;
        ///	text-align: center;
        ///	color: white;
        ///	background-color: #3366FF;	
        ///}
        ///&lt;/style&gt;
        ///
        ///&lt;div id=&quot;reporte&quot;&gt;
        ///
        ///	&lt;h5&gt;SISTEMA INTEGRAL DE CONTROL DE AUTOTRANSPORTES Y SERVICIOS&lt;/h5&gt;
        ///
        ///	&lt;h2&gt;Reporte Concentrado de Flotilla&lt;/h2&gt;
        ///	&lt;hr&gt;
        ///
        ///	&lt;div id=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReporteConcentradoFlotilla_Template {
            get {
                return ResourceManager.GetString("ReporteConcentradoFlotilla_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///#reporte {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}	
        ///
        ///table {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}
        ///
        ///td {
        ///	padding: .5em;
        ///	text-align: right;
        ///}
        ///
        ///td:first-child {
        ///	padding: .5em;
        ///	text-align: left;
        ///}
        ///
        ///th {
        ///	padding: .5em;
        ///	text-align: center;
        ///	color: white;
        ///	background-color: #3366FF;	
        ///}
        ///&lt;/style&gt;
        ///
        ///&lt;div id=&quot;reporte&quot;&gt;
        ///
        ///	&lt;h5&gt;SISTEMA INTEGRAL DE CONTROL DE AUTOTRANSPORTES Y SERVICIOS&lt;/h5&gt;
        ///
        ///	&lt;h2&gt;Reporte Comparativo de Kilometrajes y Mantenimientos&lt;/h2&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReporteKilometrajesMantenimientos_Diario_Template {
            get {
                return ResourceManager.GetString("ReporteKilometrajesMantenimientos_Diario_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///#reporte {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}	
        ///
        ///table {
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}
        ///
        ///td {
        ///	padding: .5em;
        ///	text-align: right;
        ///}
        ///
        ///td:first-child {
        ///	padding: .5em;
        ///	text-align: left;
        ///}
        ///
        ///th {
        ///	padding: .5em;
        ///	text-align: center;
        ///	color: white;
        ///	background-color: #3366FF;	
        ///}
        ///&lt;/style&gt;
        ///
        ///&lt;div id=&quot;reporte&quot;&gt;
        ///
        ///	&lt;h5&gt;SISTEMA INTEGRAL DE CONTROL DE AUTOTRANSPORTES Y SERVICIOS&lt;/h5&gt;
        ///
        ///	&lt;h2&gt;Reporte Comparativo de Kilometrajes y Mantenimientos&lt;/h2&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReporteKilometrajesMantenimientos_Mensual_Template {
            get {
                return ResourceManager.GetString("ReporteKilometrajesMantenimientos_Mensual_Template", resourceCulture);
            }
        }
    }
}
